### PR TITLE
Minor refactors

### PR DESCRIPTION
**Pull request by MisterDA**

### CODE REVIEW

**Comment by benmandrew** [comment]
The `Ocaml_ci` module paths exist in `service/pipeline.ml` and `gitlab/pipeline.ml` as well; are they unnecessary there too?

I ask because it seems the lower-bounds check for OCaml-CI is failing on something related to this.
https://ci.ocamllabs.io/github/ocurrent/ocaml-ci/commit/acb1414a03127df1d4377d55c21bbf6f5c69a156/variant/(lint-lower-bounds)#L1316-1316

**Review by maiste — APPROVED** [review]
LGTM :+1: 

EDIT: However, as Ben pointed out, there are a few places where the `OCaml_ci` module can be removed:
- https://github.com/ocurrent/ocaml-ci/blob/acb1414a03127df1d4377d55c21bbf6f5c69a156/service/pipeline.ml#L164
- https://github.com/ocurrent/ocaml-ci/blob/acb1414a03127df1d4377d55c21bbf6f5c69a156/service/pipeline.ml#L164

**Comment by MisterDA** [comment]
Fixed, thanks!

**Comment by benmandrew** [comment]
Brilliant, lower-bounds now works!

**Pull request merged**
