### PR TITLE
Fix opam 2.1 support

### PR DESCRIPTION
**Pull request by samoht**
The parsing of variants was completely broken. Also add a few tests to
ensure this works as expected.

Related to #416

### CODE REVIEW

**Review by kit-ty-kate — APPROVED** [review]

**Review by tmcgilchrist — APPROVED** [review]

**Comment by samoht** [comment]
I'm not totally what is the process now that I have 2 approvals :p @tmcgilchrist @talex5 should I merge and force-push to `live`?

**Comment by talex5** [comment]
Force push it to live first. If it works, merge it.

**Comment by samoht** [comment]
I've pushed it live

**Comment by samoht** [comment]
And that seems to work: https://github.com/mirage/ocaml-vchan/pull/139/checks?check_run_id=5064630256

**Pull request merged**
