### PR TITLE
UX/UI: support more features for users

### LINKED ISSUE #656: Mobile version
- [X] Organisation (#662)
  - [X] Repo (#663)
  - [X] Refs (#664)
  - [X] Build #674 
  - [ ] Step #676 
  - [ ] History #673

### PR DESCRIPTION
**Pull request by maiste**
This PR intends to fix some missing features in the ocaml-ci web UI. Here is a list of the new added:
- [ ] Fix #656:
  - [X] Organisation
  - [x] Repo
  - [x] Refs
  - [ ] Build
  - [ ] Step 
- Introduce dark mode:
  - [ ] Organisation
  - [ ] Repo
  - [ ] Refs
  - [ ] Build
  - [ ] Step

### CODE REVIEW

**Comment by maiste** [comment]
Organisation page with module support:
organisation

**Comment by maiste** [comment]
Ref page with mobile support. It uses the code introduced by @benmandrew in #660:
ref

**Comment by novemberkilo** [comment]
@maiste this is excellent thanks :) What do you think about pulling this into smaller PRs and merging things to master as you go? Perhaps at the level of each checkbox you've mentioned in the intro? Otherwise this will become quite a big PR.

**Comment by maiste** [comment]
Sure! Can do that :)

**Comment by maiste** [comment]
Closing in favour of the smaller PRs.

**Pull request closed without merging**
