### PR TITLE
Fix trailing slash in url

### PR DESCRIPTION
**Pull request by maiste**
This is an attempt to fix the problem mentioned here: https://github.com/ocurrent/ocaml-ci/issues/607#issuecomment-1379604676.

The solution comes from @cuihtlauac at https://github.com/ocaml/ocaml.org/pull/866.

### CODE REVIEW

**Comment by cuihtlauac** [comment]
Let me know if it solves your problem, I'm curious

**Comment by maiste** [comment]
Sure, no problem! On my workstation tests, it seems to fix the problem. Thanks for the solution :+1:

**Review by benmandrew — APPROVED** [review]
Works on my end 👍

**Comment by maiste** [comment]
Let's try in production, then! :)

**Pull request merged**
