### PR TITLE
Get OCaml compiler version from base image

### PR DESCRIPTION
**Pull request by talex5**
This simplifies the compiler search for duniverse builds, and is useful for the solver branch too.

### CODE REVIEW

**Comment by avsm** [comment]
Looks good to me, but how does it affect duniverse builds?

**Comment by avsm** [comment]
Scratch that last comment. I just noticed the top of the diff which simplifies the matching of compilers.

**Comment by talex5** [comment]
It's actually not quite right at the moment because duniverse wants e.g. 4.10, not 4.10.0.

**Comment by avsm** [comment]
That's something we need to refine the meaning of. I think that if a package requests "4.10", that should translate to "the latest patch version". 

Otoh, some packages might specifically ask for "4.10.1" since they need a specific version. This is rarer, but can happen sometimes.

**Pull request merged**
