### PR TITLE
Duniverse: Avoid failure when ocaml_compilers field is invalid

### PR DESCRIPTION
**Pull request by kit-ty-kate**
This should fix the issue encountered in https://github.com/realworldocaml/book/pull/3302 if it happens again in the future.

cc @avsm

Unknown errors are slightly tricky, should we put an error message web-ui per-commit pages to let the users know what happened, if that's even possible? @talex5

### CODE REVIEW

**Comment by avsm** [comment]
LGTM; I'm modifying duniverse to work with both x.y versions (which defaults to the latest patch version) and x.y.z (for a specific one). So this check is good.

**Comment by talex5** [comment]
Unit-tests are failing.

**Comment by talex5** [comment]
@kit-ty-kate : is this PR still needed? If so, it should be rebased. If not, let's close it.

**Comment by talex5** [comment]
Please re-open if this is still needed.

**Pull request closed without merging**
