### PR TITLE
Only build multicore packages on multicore compilers

### PR DESCRIPTION
**Pull request by talex5**
If a package depends on base-domains or base-effects then it requires a multicore compiler. Don't try to test it on other platforms.

Many projects want to add a sub-package with support for effects on OCaml 5.0, alongside their existing support for Lwt. This PR allows them to do that without losing CI on all older compilers. e.g.

- https://github.com/mirage/ocaml-cohttp/pull/857
- https://github.com/mirage/mirage-crypto/pull/155

### CODE REVIEW

**Comment by talex5** [comment]
Seems to work, but logs:
```
2022-05-25 14:46.05 [INFO] is_multicore "4.14.0+options" failed: Failure("unknown variant: options")
```

ocaml-version does `with_variant t (Some "options")`, but `of_string` then fails to parse this.

**Comment by talex5** [comment]
Also, lint-doc needs to handle this.

**Comment by dra27** [comment]
Flying by, somewhat, but two questions (!!): looks like a bug in `Ocaml_version.Configure_options.is_multicore` - surely that should be mapping any exception raised in parsing to `false`? More seriously, though, aren't we heading towards a state where this can/should be predicated on `"ocaml" {> 5.0.0~~}`?

**Comment by talex5** [comment]
> aren't we heading towards a state where this can/should be predicated on `"ocaml" {> 5.0.0~~}`?

Yes. This PR is only needed until we have a 5.0 compiler available in CI. Not sure when that will happen.

**Comment by dra27** [comment]
There should be an alpha0 within the next couple of weeks - the idea is that this fixes magic numbers, installation layout, and so forth. There are a few other things converging at which point alpha1 is released and we have a "normal" compiler release cycle... but CI (and tooling, etc.) should start converging on released versions as soon as alpha0 is cut.

**Review by tmcgilchrist — APPROVED** [review]

**Pull request merged**
