### PR TITLE
add sanette as user of ocaml-ci

### PR DESCRIPTION
**Pull request by sanette**

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
Thanks for your interest @sanette to start building with OCaml-CI:
 * Add the app to your account, selecting Install at https://github.com/apps/ocaml-ci
 * Select only the repositories you want tested - if you select All Repositories we won't build anything!
 
 Please let me know if you run into any issues.

**Comment by sanette** [comment]
thanks; Is there anything more I should do to have something happen? I couldn't find this in the docs

**Comment by talex5** [comment]
@tmcgilchrist maybe you need to `make deploy-stack` too?

**Comment by mtelvers** [comment]
I have done it as `docker container inspect` showed an outdated user list.

**Comment by sanette** [comment]
it's working now, thanks

**Comment by tmcgilchrist** [comment]
Thanks for fixing the deploy @mtelvers

**Pull request merged**
