### PR TITLE
opam-monorepo 0.1.0: use released version

### PR DESCRIPTION
**Pull request by emillon**
This bumps the commit to use the released version.

### CODE REVIEW

**Comment by emillon** [comment]
I'd like to install the plugin from opam, but it's not available yet in the workers (and running `opam update` does not work, but I think it was not a good idea anyway).

What's a good way to deal with this?

Thanks!

**Comment by talex5** [comment]
When was it released? The base image builder ran today, so it might just be a case of asking the CI to use the newer images.

**Comment by talex5** [comment]
`opam update` is fine - just remember to `git fetch && git reset --hard` first.

**Comment by emillon** [comment]
> When was it released? The base image builder ran today, so it might just be a case of asking the CI to use the newer images.

That was merged 5 days ago: ocaml/opam-repository#17750. How can I tell the CI to use the newer images?

**Comment by talex5** [comment]
For local testing, you can just click Rebuild on the `docker pull` boxes.

**Comment by emillon** [comment]
Ah, that works. Thanks! I'll try to update this so that we can use `install_project_deps` instead of calling opam install manually here.

**Comment by emillon** [comment]
Just did so - it's now doing the normal stuff to opam install dune and opam-monorepo at the right versions.

**Review by talex5 — COMMENTED** [review]
Just putting the latest opam-repository version in the selections will force a rebuild of all monorepo targets every time there is a new commit to opam-repository. For opam builds, the solver searches backwards through the Git history to find the oldest commit with the same metadata for the selected packages. That way, irrelevant changes don't affect things. It might be worth sending a request for dune and opam-monorepo to the solver, just for that.

**Comment by emillon** [comment]
Thanks for the tip. I'll try that.

**Comment by emillon** [comment]
Done. I extracted a `solve` function and pass that to the opam-monorepo bits. I have a couple questions about that:
- I had to build a dummy opam file containing my dependencies (ocaml, opam-monorepo, dune) - is there a way around that? (by passing the constraints to the solver directly maybe?)
- this tries to solve this for all workers. since there's a strict ocaml version, this fails on "almost all" workers. should I try to filter the platforms based on the ocaml version first?

**Comment by talex5** [comment]
Yeah, should be easy to pass in just the platform you want in this case.

**Comment by emillon** [comment]
That worked. I realized that it probably won't work if a monorepo project locks a version with a different patch number (such as 4.10.0), but we can see if it's a problem later.

**Review by talex5 — APPROVED** [review]
Thanks - looks good to me!

(I moved things around a little to minimise the diff)

**Comment by emillon** [comment]
Thanks! Yes, I wasn't too sure about the `solve` interface, this looks better this way.

**Pull request merged**
