### PR TITLE
Add inhabitedtype to allowlist

### PR DESCRIPTION
**Pull request by talex5**
/cc @dinosaure

### CODE REVIEW

**Comment by dinosaure** [comment]
Thanks, I did not get any responses from @seliopou unfortunately 😕

**Comment by seliopou** [comment]
What's this now?

**Comment by dinosaure** [comment]
> What's this now?

You are able to install the OCaml CI application available here: https://github.com/apps/ocaml-ci
And configure it to launch the CI into certain repositories :+1:.

**Comment by dinosaure** [comment]
Just to re-contextualize, it seems that several projects such as `angstrom` & `bigstringaf` are widely used by MirageOS and I proposed to give you an access to OCaml-CI for such projects to help you (and us) to maintain them.

**Comment by avsm** [comment]
@seliopou there's an overview of the ocurrent CI stack over here: https://github.com/ocurrent/overview

**Comment by seliopou** [comment]
Ok I installed the app.

**Comment by talex5** [comment]
@seliopou : for now, you have to select which repositories you want it enabled for (if you select "All repositories" then it assumes that was a mistake). There's a selection list when you install it, at https://github.com/apps/ocaml-ci

**Pull request merged**
