### PR TITLE
Make GitHub settings in dev.md match the ones actually in use

### PR DESCRIPTION
**Pull request by talex5**
I'm not sure where the ones in the documentation came from, but they don't match the settings for the real deployment, which seems wrong.

/cc @maiste

### CODE REVIEW

**Comment by maiste** [comment]
@talex5, I don't have the possibility to subscribe to the events `Create` and `Push`... What about you @novemberkilo?

Screenshot:
image

**Comment by talex5** [comment]
Did you select all the permissions in the previous section? e.g. the `Create` option appears after selecting `Contents: read-only`.

**Review by tmcgilchrist — APPROVED** [review]
Thanks @talex5 this matches what I can see for the apps and my own GH App.

**Review by maiste — APPROVED** [review]
I fixed my GithubApp with all your remarks. Thanks a lot for the correction!

**Pull request merged**
