### PR TITLE
Fix x32_86bit job caused by capnproto

### PR DESCRIPTION
**Pull request by moyodiallo**
This is a temporary fix, it may take time to have new release of Debian following bookworm, that fixes capnproto.

Issue related to https://github.com/mirage/capnp-rpc/issues/273.
And a PR is addressed to capnproto https://github.com/capnproto/capnproto/pull/1824

### CODE REVIEW

**Comment by reynir** [comment]
Hi! I don't understand how since this PR is unmerged, but it seems to affect CI for us. Our test on debian x86_32 fails due to test failures in capnproto. We don't (transitively) depend on capnproto so it isn't something that should be built. Furthermore, the Dockerfile commands match exactly with this PR.

https://ocaml.ci.dev/github/robur-coop/miragevpn/commit/27f5ea3ae48bd99b8bcf1099d81ab61075020b36/variant/debian-12-5.1_x86_32_opam-2.1

**Comment by moyodiallo** [comment]
>  We don't (transitively) depend on capnproto so it isn't something that should be built. Furthermore, the Dockerfile commands match exactly with this PR.

You're right, good point. I'll fix it by testing against the dependencies. Thks.

**Comment by moyodiallo** [comment]
> Hi! I don't understand how since this PR is unmerged, but it seems to affect CI for us.

I deployed it by merging it to the live-engine branch in order to test it before merging it on master branch.

**Comment by reynir** [comment]
> > Hi! I don't understand how since this PR is unmerged, but it seems to affect CI for us.
> 
> I deployed it by merging it to the live-engine branch in order to test it before merging it on master branch.

Ah good, I am relieved to hear this. For a few minutes I was worried any latest commit or PR was used to build the docker image(!)

**Comment by moyodiallo** [comment]
Thanks for that report, I deployed the fix and It's working. https://ocaml.ci.dev/github/robur-coop/miragevpn/commit/c2dc140344a1d971de7f8e1b042822b2109c39ed.

**Comment by benmandrew** [comment]
@moyodiallo can this be merged?

**Comment by moyodiallo** [comment]
> @moyodiallo can this be merged?

Not yet, this PR needs some further discussion with @tmcgilchrist.

**Comment by moyodiallo** [comment]
After a discussion with @tmcgilchrist, it is preferable to not add patched system libraries in the CI. So this PR is replaced by https://github.com/ocurrent/ocaml-ci/pull/902.

**Comment by moyodiallo** [comment]
This won't be merged.

**Comment by moyodiallo** [comment]
This won't be merged.

**Comment by reynir** [comment]
Hi this seems to be back and making unrelated builds fail :(

**Comment by reynir** [comment]
https://ocaml.ci.dev/github/robur-coop/miragevpn/commit/3d5d67c28361710b88394fe7509180175e6253c9/variant/debian-12-5.1_x86_32_opam-2.1

**Comment by moyodiallo** [comment]
Sorry the there is wrong deployment, I will fixed that. The master branch is free from this error.

**Comment by moyodiallo** [comment]
After verification and new deployment without this fix, the error wasn't coming from this. This is related to https://github.com/ocurrent/ocaml-ci/issues/914.

**Comment by reynir** [comment]
Well it is still building capnproto in the build I posted above even if it
is unrelated to the package being built.

**Pull request closed without merging**
