### PR TITLE
Link to the git forge within Ref Branches list

### PR DESCRIPTION
**Pull request by MisterDA**
I think it's nice to have a link to the Git forge here considering we're showing the forge log and the PR/MR id as well.

### CODE REVIEW

**Comment by maiste** [comment]
This is something that will require more important refactoring. There is a lot of duplication in the code for both forge, but the plan is to do the refactoring once both versions run (GitHub and Gitlab) well in the copy system.

**Comment by MisterDA** [comment]
Well if we're going to refactor everything where's the harm in merging this?

**Comment by maiste** [comment]
Two reasons here why I'm reluctant to merge the PR: it is interfering with conforming the `gitlab` views to the new design, and this work will be erased when we merge `gitlab` and `github` views.

**Comment by MisterDA** [comment]
Ok, I trust you on this :)

**Comment by maiste** [comment]
Thanks! :pray: Here is the issue to track the progression of the refactoring task https://github.com/ocurrent/ocaml-ci/issues/645

**Pull request closed without merging**
