### PR TITLE
Wider and lighter logs

### PR DESCRIPTION
**Pull request by novemberkilo**
Addressing some of the issues raised in #607 this PR

- reduces the size of the font used in the logs
- increases utility of horizontal real estate 
- replaces the dark background with a light one

// @kit-ty-kate @samoht @emillon @talex5 

Before:

Screen Shot 2022-11-23 at 11 56 50 am

After:

Screen Shot 2022-11-23 at 11 55 34 am

### CODE REVIEW

**Comment by novemberkilo** [comment]
Good catch @benmandrew thanks. I was experimenting with tailwind's dark/light support and didn't completely reverse that out (decided to stay with the one theme and not switch anything according to dark/light preferences). Now fixed.

**Comment by novemberkilo** [comment]
@maiste acknowledging that I have made updates to the gitlab step pages as well. If you could please verify by running things locally that would be great. Thanks.

**Review by maiste — APPROVED** [review]
Thanks! Good to go :+1:

**Review by benmandrew — APPROVED** [review]
Works on my end now 👍

**Pull request merged**
