### PR TITLE
Mobile version: ref page

### PR DESCRIPTION
**Pull request by maiste**
This is part of https://github.com/ocurrent/ocaml-ci/issues/656. It supersedes a part of https://github.com/ocurrent/ocaml-ci/pull/657.

It needs #663 to be merged first.

In the mobile version, I removed much information to make it more transparent for the users when reading on a small screen. The details information will be available on the build page. It uses parts of  Ben's CSS trick to truncate the code (#660).

### CODE REVIEW

**Comment by maiste** [comment]
ref

**Comment by benmandrew** [comment]
Commit messages are not truncating correctly, it seems the containing div is slightly too long and so the ellipses are hidden by the `truncate` class.

Screenshot 2022-12-07 at 12 59 15

**Review by benmandrew — CHANGES_REQUESTED** [review]
Above

**Review by novemberkilo — APPROVED** [review]
Thanks @maiste - as with the other 'mobile version' PRs ... still some issues with Safari on mobile but overall much improved so happy to ship.

**Pull request merged**
