### PR TITLE
Constrain Alcotest to pre 1.0.0

### PR DESCRIPTION
**Pull request by CraigFe**
While we wait for 1.0.1 to become available in CI.

### CODE REVIEW

**Comment by CraigFe** [comment]
I'm not sure why the CI is still failing here.
```
#19 30.25 # Error: Conflict between the following libraries:
#19 30.25 # - "current_rpc" in _build/default/ocurrent/lib_rpc
#19 30.25 # - "current_rpc" in /home/opam/.opam/4.08/lib/current_rpc
#19 30.25 #   -> required by library "ocaml-ci-api" in
#19 30.25 #      /home/opam/.opam/4.08/lib/ocaml-ci-api
#19 30.25 # -> required by executable main in client/dune:4
```

**Comment by talex5** [comment]
Looks like something changed in dune 2.2.0 - probably https://github.com/ocaml/dune/pull/3075.

Maybe we should use an opam pin instead of a submodule now?

**Comment by talex5** [comment]
I've asked about this in https://github.com/ocaml/dune/issues/3139 in case there's a better solution.

**Comment by CraigFe** [comment]
Done in https://github.com/ocurrent/ocaml-ci/pull/108/commits/556fc0e7a87bc848c9f559ced3aae1826cf16835. I'm not against pinning in principle, but:
 - it's messy here since we need to pin transitive dependencies in the same repository;
 - Dune's `.opam` file autogeneration doesn't support pinning (and likely never will, as I understand it).

**Comment by talex5** [comment]
Fixed by #111 and #121.

**Pull request closed without merging**
