### PR TITLE
Improve installation instructions

### PR DESCRIPTION
**Pull request by talex5**
Show how to install the dependencies, including pinning matrix.

### CODE REVIEW

**Comment by maiste** [comment]
It might be a dummy question, but there is something I don't understand... Why pin `ocaml-matrix` if it is in the git submodule?

**Comment by talex5** [comment]
So that we can use opam to install the dependencies.

**Review by maiste — APPROVED** [review]

**Comment by MisterDA** [comment]
Maybe it could be even better *not* to depend on packages we use in submodules as Etienne suggested, and not pin them either so that we don't "pollute" the global opam switch if any.
Instead, to install the dependencies of the submodules we could do something like this for each package we depend on in each submodule.

```sh
opam install --deps-only --with-test ./ocaml-matrix/matrix_commom.opam
```

**Comment by talex5** [comment]
The matrix dependency has gone for now, so I've removed the pins.

**Pull request merged**
