### PR TITLE
Vendored libraries update

### PR DESCRIPTION
**Pull request by kit-ty-kate**
This should fix the lack of OCaml 4.12 testing at the moment

### CODE REVIEW

**Comment by dra27** [comment]
Does avsm/ocaml-dockerfile#37 affect this?

Does this also switch Alpine testing to 3.13?

**Comment by kit-ty-kate** [comment]
no and yes respectively ^^

**Comment by avsm** [comment]
Hold off on this until the base images are updated please.

**Comment by avsm** [comment]
Merged #317 with the released versions of ocaml-dockerfile and ocaml-version.

**Pull request closed without merging**
