### PR TITLE
Update submodules

### PR DESCRIPTION
**Pull request by moyodiallo**
* Add solver-service fix for old commits: https://github.com/ocurrent/solver-service/pull/35

### CODE REVIEW

**Review by maiste — APPROVED** [review]
I thought @tmcgilchrist reverted this commit for the `solver-service` `live` branch because it was causing issues. Was it the case, or was it the representation of another bug?

**Comment by moyodiallo** [comment]
> I thought @tmcgilchrist reverted this commit for the `solver-service` `live` branch because it was causing issues. Was it the case, or was it the representation of another bug?

It is a representation of another bug.

**Review by maiste — COMMENTED** [review]
From the offline discussion, the bug I mentioned was separated from the commit in this PR.

**Review by maiste — APPROVED** [review]
Good to go :+1:

**Pull request merged**
