### PR TITLE
Allow ocaml-community to run OCaml CI jobs

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
https://github.com/ocaml-community maintains a number of important packages and some of them have Travis set up which is plain broken. Migrating to OCaml CI makes a lot of sense for them.

### CODE REVIEW

**Review by kit-ty-kate — APPROVED** [review]

**Comment by tmcgilchrist** [comment]
Someone from @ocaml-community will need to approve the GH app before their builds will appear in https://ci.ocamllabs.io/github @Leonidas-from-XIV

**Comment by Leonidas-from-XIV** [comment]
@tmcgilchrist Yes, Drup set this up but unfortunately it doesn't seem to pick it up: https://github.com/ocaml-community/yojson/pull/108 Maybe something similar to https://github.com/ocurrent/ocaml-ci/pull/367 is necessary here?

**Comment by tmcgilchrist** [comment]
@Leonidas-from-XIV The change is deployed, the issue is  @ocaml-community has selected all the repos which we don't currently support. If they can select specific projects to build then they should be picked up.

FYI from the logs
```Installation "ocaml-community" has selected all repositories - skipping as probably a mistake```
https://github.com/ocurrent/ocaml-ci/issues/392

**Comment by Leonidas-from-XIV** [comment]
Thanks for looking into this again. Unfortunately I don't have admin access to the organization myself so I can't set things up myself but I'll reach out to people who do.

**Pull request merged**
