### PR TITLE
add nilsbecker

### PR DESCRIPTION
**Pull request by nilsbecker**

### CODE REVIEW

**Review by benmandrew — APPROVED** [review]
Thank you!

**Comment by benmandrew** [comment]
@nilsbecker the change is deployed, please let us know if there are any issues. Enjoy!

**Comment by nilsbecker** [comment]
so far i cannot find my account on https://ocaml.ci.dev/ ...

**Comment by mtelvers** [comment]
@benmandrew after merging we need to redeploy the stack with `make deploy-stack`.  I have done this and @nilsbecker is now visible on https://ocaml.ci.dev.

**Pull request merged**
